name: Vercel Production Deployment

on:
  push:
    branches:
      - master

# GitHub Actions runs all jobs in parallel by default
jobs:
  # JOB 1: Deploys the Patient PWA
  deploy-pwa:
    runs-on: ubuntu-latest
    # These env variables are available to all steps in THIS job
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PWA }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment Information
        run: cd patient-pwa && vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Build Project Artifacts
        run: cd patient-pwa && vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy Project Artifacts to Vercel
        run: cd patient-pwa && vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

  # JOB 2: Deploys the Clinic Dashboard
  deploy-dashboard:
    runs-on: ubuntu-latest
    # These env variables are available to all steps in THIS job
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DASHBOARD }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment Information
        run: cd clinic-dashboard && vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Build Project Artifacts
        run: cd clinic-dashboard && vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy Project Artifacts to Vercel
        run: cd clinic-dashboard && vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
